

const possibleInputs: string[] = [
    "PPPKKK",
    "P~No Input",
    "236[HP]~No Input",
    "236PP~No Input",
    "236PP~PP",
    "236236K",
    "63214KK",
    "236KKOD",
    "KKOD",
    "236KK",
    "236P~K",
    "214P~6P",
    "214PP~6P",
    "236PPOD",
    "236LP~6PLP",
    "236LP~6P~6PLP",
    "236MP~6K~6KMP",
    "236HP~6K~6KHP",
    "236LP~6KLP",
    "236MP~6P~6PMP",
    "236MP~6PMP",
    "236HP~6P~6PHP",
    "236HP~6PHP",
    "236MP~6P",
    "236HP~6P",
    "LPLK",
    "[LP]LP",
    "[MP]MP",
    "[HP]HP",
    "MPMK",
    "HPHK",
    "K~[2]",
    "MP~HK",
    "MK~HP",
    "LPLP",
    "MPMP",
    "HPHP",
    "2KK",
    "LK",
    "MK",
    "[HK]",
    "[K]",
    "HK",
    "LP",
    "MP",
    "[HP]",
    "[P]",
    "HP",
    "PP~PP",
    "PP",
    "6P",
    "4P",
    "22P (hold)",
    "2P",
    "6K",
    "4K",
    "2K",
    "KK",
    "66",
    "9",
    "Any Direction + P"
]

const column = [
    {
        title: 'Name',
        dataIndex: 'Name',
        key: 'Name',
      },
      {
        title: 'Input',
        dataIndex: 'Input',
        key: 'Input',
      },
      {
        title: 'Startup',
        dataIndex: 'Startup',
        key: 'Startup',
      },
      {
        title: 'Active',
        dataIndex: 'Active',
        key: 'Active',
      },
      {
        title: 'Recovery',
        dataIndex: 'Recovery',
        key: 'Recovery',
      },
      {
        title: 'Cancel',
        dataIndex: 'Cancel',
        key: 'Cancel',
      },
      {
        title: 'Damage',
        dataIndex: 'Damage',
        key: 'Damage',
      },
      {
        title: 'Guard',
        dataIndex: 'Guard',
        key: 'Guard',
      },
      {
        title: 'OnHit',
        dataIndex: 'OnHit',
        key: 'OnHit',
      },
      {
        title: 'OnBlock',
        dataIndex: 'OnBlock',
        key: 'OnBlock',
      },
];

const settings = {possibleInputs, column};
export default settings;